language: java
sudo: false

# ref: https://docs.travis-ci.com/user/database-setup/
services:
  - redis-server

addons:
  # ref: https://docs.travis-ci.com/user/sonarcloud/
  sonarcloud:
    organization: "y0ngb1n"
    token:
      secure: "$SONAR_TOKEN"

jdk:
  - openjdk8

script:
  - mvn clean verify sonar:sonar -Pcoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
