language: java
sudo: false

addons:
  sonarcloud:
    organization: "y0ngb1n"
    token:
      secure: "$SONAR_TOKEN"

jdk:
  - openjdk8

install:
  - pip install --user codecov

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - codecov

cache:
  directories:
    - '$HOME/.cache/pip'
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
